### ISSUE TITLE
Quarto

### ISSUE THREAD

**Issue by nsacco** [rchaput/acronymsdown#5]
Does this package work with Quarto?

**Comment by rchaput** [comment]
I have not tested Quarto myself, but according to its documentation it should work.

Below are a few steps that should be sufficient:

1. You need to have the package installed on your computer and obtain the path to the "main" script, `parse-acronyms.lua`.
  a. (Through R) You can install *acronymsdown* as a classic R package, then, in an R session, call the method `acronymsdown::path_to_filter()` and note the result somewhere. This is the path you will need later.
  b. (Manual installation) Or you can simply download the scripts as a ZIP archive from the GitHub Releases (at the time of writing, [this link](https://github.com/rchaput/acronymsdown/releases/download/v0.11.1/acronymsdown.zip) ), and extract the folder at the destination of your choice on your computer. Note the path for the next step.

2. In your Quarto document, in the metadata block, add the following lines:
```yaml
filters:
  - /your/path/to/parse-acronyms.lua
```
where `/your/path/to/parse-acronyms.lua` is the path you noted at step 1.

After that, *acronymsdown* should work.

**Comment by nsacco** [comment]
Thank you, this works very well, except that I have one file per (*.qmd) per chapter, and the long form is printed again in each chapter. Is there any solution to avoid this and define the key once? Also, working with different pages, the links are not recognized.

**Comment by rchaput** [comment]
Concerning the first problem, I assume that, based on what you are saying, Quarto renders each chapter individually. This is similar to bookdown's "Knit-Merge" strategy, as opposed to the "Merge-Knit" where all chapters are first combined then rendered. Unfortunately, if this is true, there is not much I can do from acronymsdown's side: it is called by Quarto with a clean state on each chapter, so we cannot know which keys have been already used. The only way would be to see if Quarto supports the "Merge-Knit" strategy or something similar.

Concerning the second problem, I have no idea why this does not work. The links are standard Markdown links, and should work between different pages of a same document. Maybe Quarto is doing something that impairs this, but I do not know enough to answer you.

**Comment by nsacco** [comment]
OK, thank you so much for your answers and help.
