### ISSUE TITLE
Use with Quarto

### ISSUE THREAD

**Issue by jtchittenden** [rchaput/acronymsdown#6]
Not an bug or anything, just if you want to use this with Quarto:

1. Copy the .lua files in /inst to _extensions folder in your quarto project.
2. Add the file _extension.yml with contents:
```
title: acronyms
author: "Remy Chaput (https://github.com/rchaput/acronymsdown) GPL 3.0"
version: 1.0.0
quarto-required: ">=1.2.0"
contributes:
  filters:
    - parse-acronyms.lua
```
3. Add the acronyms filter to your filters in _quarto.yml:
```
filters:
  - acronyms
```

side note: I was planning out how to do this and stumbled on this repo.  It's exactly what I needed, and more of what I wanted.  Nice work.

**Comment by vitallish** [comment]
Thanks for this guide on how to use with Quarto. I'm having a bit of trouble setting it up and I was hoping you could help.

Here is where I am:

- set up _extensions folder in my project folder with the following structure:
<img width="228" alt="image" src="https://user-images.githubusercontent.com/4785053/233847713-625f4a03-3ec8-4134-82ca-6d040cc8a7ad.png">

where _extension.yml is what recommended above.

I added filters line to _quarto.yml as well.

However, when I try to render the document I get this error:
```
Error running filter acronyms:
Could not find executable acronyms
```

I have a feeling something is wrong in the way that I placed the files in the folders - do you have any tips on how I can solve this?

**Comment by jtchittenden** [comment]
_extension.yml not _extensions.yml

At least that’s what I see.

Sent from my iPhone

On Apr 23, 2023, at 11:14 AM, vitallish ***@***.***> wrote:

﻿

Thanks for this guide on how to use with Quarto. I'm having a bit of trouble setting it up and I was hoping you could help.

Here is where I am:

  *   set up _extensions folder in my project folder with the following structure:

[image]<https://user-images.githubusercontent.com/4785053/233847713-625f4a03-3ec8-4134-82ca-6d040cc8a7ad.png>

where _extension.yml is what recommended above.

I added filters line to _quarto.yml as well.

However, when I try to render the document I get this error:

Error running filter acronyms:
Could not find executable acronyms


I have a feeling something is wrong in the way that I placed the files in the folders - do you have any tips on how I can solve this?

**Comment by rchaput** [comment]
I am not very familiar with Quarto (and I take the occasion to thank @jtchittenden for providing this solution!), but I can confirm it works with the following setup:

```
├── _extensions
│   └── acronyms
│       ├── _extension.yml
│       ├── acronyms.lua
│       ├── acronyms_styles.lua
│       ├── parse-acronyms.lua
│       └── sort_acronyms.lua
└──hello.qmd
```

where `_extension.yml` contains:
```
title: acronyms
author: rchaput
version: 1.0.0
quarto-required: ">=1.2.0"
contributes:
  filters:
    - parse-acronyms.lua
```
(essentially what was recommended by jtchittenden), the Lua files are from a fresh installation of acronymsdown (download zip from releases, `unzip acronymsdown.zip && mv acronymsdown/inst/*.lua _extensions/acronyms/`), and `hello.qmd` contains:
```qmd
---
title: "Quarto Basics"
format: html

filters:
  - acronyms

acronyms:
  keys:
    - shortname: RL
      longname: Reinforcement Learning
---

# Introduction {#intro}

This paragraph mentions \acr{RL} for the first time.

And now, in this paragraph, \acr{RL} is in short form.
```

**Comment by vitallish** [comment]
> ```gfm
> This paragraph mentions \acr{RL} for the first time.
> ```

Yes i'm sorry - that was my mistake! extension.yml vs extensions.yml

**Comment by espinielli** [comment]
FYI I set a proper Quarto extension [repo for acronyms](https://github.com/espinielli/acronyms).
I need it to share and for easy installations with colleagues.
I kept `rchaput` as author in the `extension.yml`.

I would be happy to transfer the repo/extension over to `rchaput` any time.

HTH

**Comment by jtchittenden** [comment]
Thanks for this. When I get a chance, I’ll move some code I use to allow markdown in the longname and shortname and a couple other enhancements.

Sent from my iPhone

On Jun 5, 2023, at 11:20 AM, Enrico Spinielli ***@***.***> wrote:

﻿

FYI I set an proper Quarto extension repo for acronyms<https://github.com/espinielli/acronyms>.
I need it to share and easy installations with colleagues.
I kept rchaput as author in the extension.yml.

I would be happy to transfer the repo/extension over to rchaput any time.

HTH

**Comment by espinielli** [comment]
That would be great!

**Comment by rchaput** [comment]
Nice, thank you espinielli, that is an excellent idea! Thank you for the proposition, but you can keep your repository.
I will provide a Quarto version at some point, I just need to figure out the "best" way, since RMarkdown and Quarto use different folder structures (but the same Lua code can be used).

At the very least, I think I can create a new `quarto` branch with the same content as your repo, so that users can `quarto add rchaput/acronymsdown@quarto`.

**Comment by espinielli** [comment]
ok.
One issue I am already facing is OS dependency...on MS Windows the loading of the local Lua modules fails, while on MacOS I had no problems...

**Comment by jtchittenden** [comment]
I placed all my filters into a package and provide a function that sort of replicates the r markdown template feature, creating a directory for a report as a quarto project with the filters all set up in a subdirectory. I haven’t seen a problem on Mac or centos7.

Sent from my iPhone

On Jun 6, 2023, at 12:02 PM, Enrico Spinielli ***@***.***> wrote:

﻿

ok.
One issue I am already facing is OS dependency...on MS Windows the loading of the local Lua modules fails, while on MacOS I had no problems...

**Comment by aelmokadem** [comment]
Thank you so much for the wonderful package. 
I am creating a quarto book and followed the instructions by adding the `_extension` files then adding these lines to the `_quarto.yml` file:
```
filters:
  - acronyms
acronyms:
  loa_title: "Glossary"
  insert_loa: "end"
  sorting: alphabetical
  keys:
    - shortname: UN
      longname: United Nations
  # Warning! The following path must be either absolute or relative to the 
  # current working directory! 
  # (You can have multiple acronym files)
  fromfile: 
    - _extensions/acronyms/acronyms.yml
```

Then I added a `acr{RL}` to the `intro.qmd` file as a test.

However, I am getting an error when I render the book:

```
Error running filter /Applications/quarto/share/filters/main.lua:
...macometricsJulia/_extensions/acronyms/parse-acronyms.lua:109: attempt to index a nil value (global 'Acronyms')
stack traceback:
        [C]: in ?
        [C]: in method 'walk'
        /Applications/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
        /Applications/quarto/share/filters/main.lua:449: in local 'callback'
        [string "..."]:1789: in field 'withScriptFile'
        /Applications/quarto/share/filters/main.lua:452: in upvalue 'run_emulated_filter_chain'
        /Applications/quarto/share/filters/main.lua:495: in function </Applications/quarto/share/filters/main.lua:476>
stack traceback:
        /Applications/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
        /Applications/quarto/share/filters/main.lua:449: in local 'callback'
        [string "..."]:1789: in field 'withScriptFile'
        /Applications/quarto/share/filters/main.lua:452: in upvalue 'run_emulated_filter_chain'
        /Applications/quarto/share/filters/main.lua:495: in function </Applications/quarto/share/filters/main.lua:476>
```

Any ideas what I have done wrong here!

Thanks.

**Comment by rchaput** [comment]
This is the same problem as previously described.

I have created a new repository for the Quarto version (I initially wanted to create a separate branch, but this would not let me change the website documentation easily...): [rchaput/acronyms](https://github.com/rchaput/acronyms)

I will change this repository to announce the new one in the Readme in the next days; I wanted first to make sure that all tests were passing with the new version.
It is specially made for Quarto and should not have this bug. I will also try to add a few improvements specific to Quarto, so any Quarto user should refer to the new repo instead. For the moment, it has the same features as the RMarkdown one (but easier to use).

**Comment by aelmokadem** [comment]
@rchaput  thank you so much. I will definitely try that.
